// Window navigation guards — shared by the main window and artifact popout windows
// (F059c) so the top-level navigation security can't drift between them.
//
// Policy (defense-in-depth; the renderer eventually shows LLM/MCP-produced content):
//   - window.open / target=_blank → always denied; https:// is handed to the system
//     browser, everything else is dropped.
//   - in-page navigation (will-navigate) → only the app's own assets are allowed
//     (dev: the Vite dev-server origin; prod: the exact app://space origin).
//     https:// links open externally; any other scheme/path is prevented (blocks
//     file:///etc/passwd-style injection).
//
// `import type` only — no runtime electron import, so this module is safe to pull
// into the tsx test loader.

import type { WebContents } from 'electron';
import { isArtifactHtmlFrameUrl } from './app-protocol-policy.js';
import { isProjectWebPreviewUrl } from './project-web-preview.js';
import { isSpaceExtensionFrameUrl } from './space-extension-frame.js';
import { normalizeWebPreviewUrl } from '@kodax-space/space-ipc-schema';
import { remoteWebPreviewRegistry, type PreviewFrame } from './remote-web-preview.js';

export interface NavGuardDeps {
  /** Vite dev-server URL when running in dev; undefined in production. */
  readonly devServerUrl: string | undefined;
  /** Exact privileged application origin used by packaged renderer assets. */
  readonly allowedAppOrigin?: string;
  /** Optional trusted data: URLs generated by the main process, matched exactly. */
  readonly allowedDataUrls?: readonly string[];
  /** Open an external https URL in the system browser (inject shell.openExternal). */
  readonly openExternal: (url: string) => void;
}

/** Lock a window's top-level navigation + window.open to the app's own assets. */
export function installNavigationGuards(wc: WebContents, deps: NavGuardDeps): void {
  wc.setWindowOpenHandler(({ url }) => {
    if (url.startsWith('https://')) deps.openExternal(url);
    return { action: 'deny' };
  });

  wc.on('will-navigate', (event, url) => {
    if (isSpaceExtensionFrameUrl(url)) {
      event.preventDefault();
      return;
    }
    let parsedUrl: URL | null = null;
    try {
      parsedUrl = new URL(url);
    } catch {
      // Invalid URL stays denied below.
    }
    const isDevServer = Boolean(
      deps.devServerUrl &&
      parsedUrl?.username === '' &&
      parsedUrl.password === '' &&
      parsedUrl.origin === new URL(deps.devServerUrl).origin,
    );
    const isAllowedApplicationUrl = Boolean(
      deps.allowedAppOrigin &&
      parsedUrl &&
      parsedUrl.username === '' &&
      parsedUrl.password === '' &&
      `${parsedUrl.protocol}//${parsedUrl.host}` === deps.allowedAppOrigin,
    );
    const isAllowedDataUrl = deps.allowedDataUrls?.includes(url) ?? false;
    if (isDevServer || isAllowedApplicationUrl || isAllowedDataUrl) return;

    event.preventDefault();
    if (url.startsWith('https://')) deps.openExternal(url);
  });

  // Child frames require a window-owned remote grant or a local preview/extension endpoint.
  const guardSubframeNavigation = (details: {
    readonly url: string;
    readonly isMainFrame: boolean;
    readonly frame?: PreviewFrame | null;
    preventDefault(): void;
  }): void => {
    if (details.isMainFrame) return;
    if (remoteWebPreviewRegistry.forFrame(wc.id, details.frame ?? null, wc.mainFrame)) {
      if (!normalizeWebPreviewUrl(details.url)) details.preventDefault();
      return;
    }
    if (
      isProjectWebPreviewUrl(details.url) ||
      isArtifactHtmlFrameUrl(details.url) ||
      isSpaceExtensionFrameUrl(details.url)
    )
      return;
    details.preventDefault();
  };
  wc.on('will-frame-navigate', guardSubframeNavigation);
  wc.on('will-redirect', guardSubframeNavigation);
}
